<!DOCTYPE html>
<html lang="en">
<?php
require_once __DIR__ . '/partials/header.php';


?>

<body>
    <div class="back-dash">
        <?php require __DIR__ . '/partials/sidebarAdmin.php'; ?>

        <!-- Main content area -->
        <div class="main-content">
            <div class="stat-card">
                <div class="stat-header">
                    <div class="flex-min">
                        <h2 class="stat-title">
                            <i class="las la-bug"></i>
                            Error log
                        </h2>
                        <p>Autogenerated <i>VETCAMP</i> crash report for development purposes. </p>
                    </div>
                    <a target="_blank" class="main-action-bright tertiary" href="/admin/dev/errors/download">
                        <i class="las la-download"></i>
                        Download
                    </a>
                </div>
                <div class="stat-number">

                    <table class="error-table">
                        <tr>
                            <th>Type</th>
                            <th>Date</th>
                            <th>Error</th>
                            <th>File</th>
                            <th>Trace</th>
                        </tr>
                        <tbody>
                            <?php foreach ($errors as $error): ?>
                                <tr>
                                    <td class="error-type-<?= $error['type'] ?>" ><?= $error['type'] ?></td>
                                    <td><?= $error['date'] ?></td>
                                    <td><?= $error['error'] ?></td>
                                    <td><?= $error['file'] ?></td>
                                    <td><?= $error['trace'] ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    
                </div>
                <!-- <textarea name="errorlog" id="log-ta" class="log-ta"><?= $errors ?></textarea> -->
            </div>
        </div>
    </div>
</body>

</html>